import Header from '@/components/header/page'
import './globals.css'
import { Inter, Montserrat } from "next/font/google";
import Footer from '@/components/footer/page';

const inter = Inter({ subsets: ['latin'] })
const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-montserrat" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${montserrat.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
